# Generated by Django 6.0 on 2026-01-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nama_lengkap',
            field=models.CharField(default='-', max_length=255),
            preserve_default=False,
        ),
    ]
