# Generated by Django 6.0 on 2026-02-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_nama_lengkap'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawatInap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_rawat', models.CharField(max_length=255)),
                ('tgl_masuk', models.DateTimeField()),
                ('tgl_keluar', models.DateTimeField(blank=True, null=True)),
                ('stts_pulang', models.CharField(blank=True, choices=[('Atas Persetujuan Dokter', 'Atas Persetujuan Dokter'), ('Membaik', 'Membaik'), ('Pindah Kamar', 'Pindah Kamar'), ('Sembuh', 'Sembuh'), ('Atas Permintaan Sendiri', 'Atas Permintaan Sendiri'), ('Meninggal', 'Meninggal')], max_length=50, null=True)),
            ],
            options={
                'db_table': 'rawat_inap',
            },
        ),
    ]
