# Generated by Django 6.0 on 2026-02-10 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_create_rawat_inap_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kasus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulan', models.CharField(max_length=4)),
                ('tahun', models.CharField(max_length=5)),
                ('bor', models.FloatField()),
                ('los', models.FloatField()),
                ('gdr', models.FloatField()),
            ],
            options={
                'db_table': 'kasus',
            },
        ),
    ]
