# Generated by Django 6.0 on 2026-02-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_create_kasus_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rekomendasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rekomendasi', models.TextField()),
                ('jenis_rekomendasi', models.CharField(choices=[('pelayanan medis', 'Pelayanan Medis'), ('kepegawaian', 'Kepegawaian')], max_length=20)),
            ],
            options={
                'db_table': 'rekomendasi',
            },
        ),
    ]
