# Generated by Django 6.0.2 on 2026-02-18 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_create_rekomendasi_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='KasusRekomendasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kasus', models.ForeignKey(db_column='id_kasus', on_delete=django.db.models.deletion.CASCADE, to='main.kasus')),
                ('rekomendasi', models.ForeignKey(db_column='rekomendasi_id', on_delete=django.db.models.deletion.CASCADE, to='main.rekomendasi')),
            ],
            options={
                'db_table': 'kasus_rekomendasi',
                'unique_together': {('kasus', 'rekomendasi')},
            },
        ),
    ]
