# Generated by Django 4.2.7 on 2026-04-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_kasusrekomendasi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('direktur', 'Direktur'), ('yangmed', 'Yangmed'), ('kepegawaian', 'Kepegawaian'), ('rs', 'RS')], max_length=20),
        ),
    ]
