# Generated by Django 4.2.7 on 2026-05-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_kasusrekomendasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawatinap',
            name='tempat_tidur',
            field=models.IntegerField(default=65),
        ),
    ]
