# Generated by Django 4.2.7 on 2026-05-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawatinap',
            name='tempat_tidur',
            field=models.IntegerField(default=65),
        ),
    ]
