# Generated by Django 4.2.7 on 2026-05-08 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rawatinap_tempat_tidur'),
    ]

    operations = [
    ]
